version: '3.7'

services:
  dockerapi:
    image: fleet-api:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=fleetdb;username=fleetuser;password=fleetpassword"
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "fleetuser"
      POSTGRES_PASSWORD: "fleetpassword"
      POSTGRES_DB: "fleetdb"
volumes:
  db_volume:
